### PR TITLE
fix: qwtb: executer masked some errors

### PR DESCRIPTION
**Pull request by KaeroDot**
at some point, all errors were presented as 'no calculation setup found', although the real error was different.

### CODE REVIEW

**Comment by smaslan** [comment]
try again with up to date version of source file qwtb_exec_algorithm.m :)

**Comment by smaslan** [comment]
try again with up to date version of source file qwtb_exec_algorithm.m :)

**Comment by smaslan** [comment]
No need, fixed already.

**Comment by KaeroDot** [comment]
there was no conflict, learn git merge!

**Pull request closed without merging**
